"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createRequestsBucket = exports.createRequestsController = exports.headRequest = exports.optionsRequest = exports.deleteRequest = exports.putRequest = exports.patchRequest = exports.postRequest = exports.getRequest = void 0;
const request_1 = require("./services/request");
Object.defineProperty(exports, "getRequest", { enumerable: true, get: function () { return request_1.getRequest; } });
Object.defineProperty(exports, "postRequest", { enumerable: true, get: function () { return request_1.postRequest; } });
Object.defineProperty(exports, "patchRequest", { enumerable: true, get: function () { return request_1.patchRequest; } });
Object.defineProperty(exports, "putRequest", { enumerable: true, get: function () { return request_1.putRequest; } });
Object.defineProperty(exports, "deleteRequest", { enumerable: true, get: function () { return request_1.deleteRequest; } });
Object.defineProperty(exports, "optionsRequest", { enumerable: true, get: function () { return request_1.optionsRequest; } });
Object.defineProperty(exports, "headRequest", { enumerable: true, get: function () { return request_1.headRequest; } });
Object.defineProperty(exports, "createRequestsController", { enumerable: true, get: function () { return request_1.createRequestsController; } });
Object.defineProperty(exports, "createRequestsBucket", { enumerable: true, get: function () { return request_1.createRequestsBucket; } });
